pythonizame/apps/jobboard/urls.py
from django.conf.urls import url

from pythonizame.apps.jobboard.views import (JobbordListView, JobDetailView, JobAddView)
from pythonizame.apps.jobboard.views import (JobbordMyJobsListView, JobEditView, JobDeleteView, JobChangeToReviewView)


app_name = "jobboard"

urlpatterns = [
    url(r'^job/list/', JobbordListView.as_view(), name='list'),
    url(r'^job/my-list/', JobbordMyJobsListView.as_view(), name='my-list'),
    url(r'^job/add/', JobAddView.as_view(), name='add'),
    url(r'^job/edit/(?P<job_id>[0-9]+)/', JobEditView.as_view(), name='edit'),
    url(r'^job/detail/(?P<pk>[0-9]+)/', JobDetailView.as_view(), name='detail'),
    url(r'^job/delete/(?P<job_id>[0-9]+)/', JobDeleteView.as_view(), name='delete'),
    url(r'^job/change-to-review/(?P<job_id>[0-9]+)/', JobChangeToReviewView.as_view(), name='change-to-review')
]

pythonizame/urls.py
from django.conf.urls import include, url
from django.contrib.flatpages import views
from django.contrib import admin
from django.conf.urls.static import static
from pythonizame.core.json_settings import json_settings

settings = json_settings()

urlpatterns = [
    url(r'^pymin/', include(admin.site.urls)),
    url(r'^videos/', include('pythonizame.apps.videos.urls', namespace='videos')),
    url(r'^', include('pythonizame.apps.books.urls', namespace='books')),
    url(r'^', include('pythonizame.apps.blog.urls', namespace='blog')),
    url(r'^account/', include('pythonizame.apps.account.urls', namespace='account')),
    url(r'^security/', include('pythonizame.apps.security.urls', namespace='security')),
    url(r'^jobboard/', include('pythonizame.apps.jobboard.urls', namespace='jobboard')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if not settings['AMAZON']['S3']['USE_S3']:
    from pythonizame import settings as setts
    urlpatterns += static(setts.MEDIA_URL, document_root=setts.MEDIA_ROOT)


urlpatterns += [
    url(r'^(?P<url>.*/)$', views.flatpage),
]

pythonizame/apps/jobboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django_countries.fields import CountryField


class JobCategory(models.Model):
    name = models.CharField(max_length=500, help_text=_("Nombre de la categoría del trabajo"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Categoría de empleo")
        verbose_name_plural = _("Categorías de empleo")


class Job(models.Model):
    SCHEDULE_CHOICES = (
        (1, _("Tiempo completo")),
        (0, _("Tiempo parcial"))
    )

    STATUS_TYPE = (
        (0, _("Rechazado")),
        (1, _("Aprobado")),
        (2, _("Borrador")),
        (3, _("En revisión")),
    )

    created_by = models.ForeignKey(User, verbose_name=_("Creado por"), help_text=_("Usuario que crea la vacante"))
    title = models.CharField(max_length=800, help_text=_("Título del trabajo"), verbose_name=_("Título"))
    description = models.TextField(max_length=2000, help_text=_("Describa de manera clara el puesto de trabajo"),
                                   verbose_name=_("Descripción"))
    categories = models.ManyToManyField(JobCategory, help_text=_("Categorías a la que aplica la vacante"),
                                        verbose_name=_("Categorías"))
    salary = models.CharField(max_length=600, help_text=_("Describe el salario a ofrecer por la vacante"),
                              verbose_name=_("Salario"))
    country = CountryField()
    address = models.CharField(max_length=500, null=True, blank=True, help_text=_("Ubicación del puesto"),
                               verbose_name=_("Dirección"))
    remote_working = models.BooleanField(default=False, help_text=_("¿Se acepta trabajo desde casa?"),
                                         verbose_name=_("Remoto"))
    work_schedule = models.IntegerField(choices=SCHEDULE_CHOICES, default=1, verbose_name=_("Horario"))
    # Información de la empresa.
    company_name = models.CharField(max_length=1000, help_text=_("Nombre de la empresa que propone la vacante"),
                                    verbose_name=_("Nombre de la empresa"))
    contact_email = models.CharField(max_length=1000, help_text=_("Email donde serán enviadas las aplicaciones"),
                                     verbose_name=_("Email de contacto"))
    website = models.URLField(null=True, blank=True, verbose_name=_("Sitio web"))
    status = models.IntegerField(choices=STATUS_TYPE, default=2)
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name=_("Fecha de creación"))
    # Usuario que aprueba su autorización
    approval_datetime = models.DateTimeField(auto_now_add=True, verbose_name=_("Fecha de aprobación"))
    approved_by = models.ForeignKey(User, related_name='approved_by', null=True, blank=True)
    num_of_views = models.IntegerField(default=0, help_text=_("Número de impresiones de tu job"))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Empleo")
        verbose_name_plural = _("Empleos")

pythonizame/apps/jobboard/forms.py
from django import forms
from django.utils.translation import ugettext as _

from pythonizame.apps.jobboard.models import Job


class JobForm(forms.ModelForm):

    class Meta:
        model = Job
        exclude = ['created_by', 'approval_datetime', 'approved_by', 'status', 'num_of_views']
        labels = {
            "title": _("Título"),
            "description": _("Descripción"),
            "categories": _("Categorías"),
            "salary": _("Salario"),
            "country": _("País"),
            "address": _("Dirección"),
            "remote_working": _("¿Trabajo vía remota?"),
            "work_schedule": _("Horario"),
            "company_name": _("Nombre de la empresa"),
            "contact_email": _("Email de contacto"),
            "website": _("Sitio Web"),
        }

pythonizame/apps/jobboard/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.views.generic import View, DetailView, CreateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.urls import reverse_lazy
from django.utils.translation import ugettext as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django_countries import countries
from django_countries import Countries
from django.template.loader import render_to_string
from .models import JobCategory, Job
from .forms import JobForm
from pythonizame.core.json_settings import json_settings
from pythonizame.apps.security.functions import send_email


settings = json_settings()


class JobbordListView(View):
    template_name = "jobboard_list.html"

    def get_available_countries(self):
        try:
            country_codes = list(set(list(Job.objects.filter(status=1).values_list('country', flat=True))))
        except:
            country_codes = []
        return country_codes

    def get(self, request):
        """
        Devolvemos consulta de publicaciones al usuario
        """
        country_codes = self.get_available_countries()
        kwargs = {'status': 1}
        if 'q' in request.GET and request.GET['q']:
            kwargs['description__icontains'] = request.GET['q']
        partial = request.GET['partial'] if 'partial' in request.GET else None
        full = request.GET['full'] if 'full' in request.GET else None
        if partial != full:
            if partial == "1":
                kwargs['work_schedule'] = 0
            else:
                kwargs['work_schedule'] = 1
        if 'country' in request.GET and request.GET['country'] and request.GET['country'] != "0":
            kwargs['country'] = request.GET['country']
            selected_country = kwargs['country']
        else:
            selected_country = None
        queryset = Job.objects.filter(**kwargs).order_by('-approval_datetime')
        paginator = Paginator(queryset, 5)
        if 'page' in request.GET and request.GET['page']:
            my_page = int(request.GET['page'])
        else:
            my_page = 1
        try:
            object_list = paginator.page(my_page)
        except PageNotAnInteger:
            object_list = paginator.page(1)
        except EmptyPage:
            object_list = paginator.page(paginator.num_pages)
        categories = JobCategory.objects.all()
        ctx = {'object_list': object_list,
               'page_obj': object_list,
               'selected_country': selected_country,
               'available_countries': country_codes,
               'q': request.GET['q'] if 'q' in request.GET else None,
               'full': request.GET['full'] if 'full' in request.GET else None,
               'partial': request.GET['partial'] if 'partial' in request.GET else None,
               'country': request.GET['country'] if 'country' in request.GET else None,
               'categories': categories,
               'countries': countries}
        return render(request, self.template_name, ctx)


class JobbordMyJobsListView(View):
    template_name = "jobboard_my_list.html"

    def get(self, request):
        """
        Devolvemos consulta los jobs de un usuario
        """
        if 'q' in request.GET and request.GET['q']:
            search_words = request.GET['q']
            queryset = Job.objects.filter(created_by=request.user).order_by('-approval_datetime')
        else:
            search_words = ""
            queryset = Job.objects.filter(created_by=request.user).order_by('-approval_datetime')
        paginator = Paginator(queryset, 10)
        if 'page' in request.GET and request.GET['page']:
            my_page = int(request.GET['page'])
        else:
            my_page = 1
        try:
            object_list = paginator.page(my_page)
        except PageNotAnInteger:
            object_list = paginator.page(1)
        except EmptyPage:
            object_list = paginator.page(paginator.num_pages)
        ctx = {'object_list': object_list,
               'page_obj': object_list,
               'queryset': search_words}
        return render(request, self.template_name, ctx)


class JobDetailView(DetailView):
    model = Job
    template_name = 'job_detail.html'

    def get_context_data(self, **kwargs):
        context = super(JobDetailView, self).get_context_data(**kwargs)
        if self.request.user != context['job'].created_by:
            context['job'].num_of_views += 1  # Aumentamos las visitas
            context['job'].save()
        return context


class JobChangeToReviewView(View):

    def get(self, request, job_id):
        job = get_object_or_404(Job, id=job_id, created_by=request.user)
        job.status = 3
        job.save()
        # mandamos un correo para notificar a los administradores que se mandó a revisión un nuevo empleo
        try:
            users = User.objects.filter(is_staff=True)
        except:
            users = None

        for admin in users:
            to_email = admin.email
            contenido = render_to_string("mail/change_status_job_template.html", {'url_server': settings['URL_SERVER'],
                                                                        'username': admin.username,
                                                                        'job': job.title,
                                                                        'status': job.status})
            send_email("Cambio de estatus del empleo", content=contenido, to=to_email, content_type="text/html")

        messages.success(request, _("¡Gracias! Hemos recibido tu solicitud de revisión. Muy pronto "
                                    "te enviaremos una respuesta :D"))
        return HttpResponseRedirect(reverse_lazy('jobboard:my-list'))


class JobAddView(LoginRequiredMixin, View):
    template_name = "job_add.html"
    form = JobForm

    def get(self, request):
        ctx = {'form': self.form}
        return render(request, self.template_name, ctx)

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            job = form.save(commit=False)
            job.created_by = request.user
            job.save()
            form.save_m2m()
            #mandamos un correo para notificar a los administradores que se agregó un nuevo empleo
            try:
                users = User.objects.filter(is_staff=True)
            except:
                users = None

            for admin in users:
                to_email = admin.email
                contenido = render_to_string("mail/new_job_template.html", {'url_server': settings['URL_SERVER'],
                                                                               'username': admin.username,
                                                                               'job': job.title,
                                                                               'status': job.status})
                send_email("Nuevo registro de empleo", content=contenido, to=to_email, content_type="text/html")

            messages.success(request, _("Guardado correctamente"))

            return HttpResponseRedirect(reverse_lazy('jobboard:my-list'))
        else:
            ctx = {'form': form}
            messages.error(request, _("Verifique la información enviada"))
            return render(request, self.template_name, ctx)


class JobEditView(LoginRequiredMixin, View):
    template_name = "job_edit.html"
    form = JobForm

    def get(self, request, job_id):
        job = get_object_or_404(Job, id=job_id, created_by=request.user)
        form = self.form(instance=job)
        ctx = {'form': form, 'job': job}
        return render(request, self.template_name, ctx)

    def post(self, request, job_id):
        job = get_object_or_404(Job, id=job_id, created_by=request.user)
        form = self.form(request.POST, instance=job)
        if form.is_valid():
            job = form.save(commit=False)
            job.save()
            form.save_m2m()
            messages.success(request, _("Guardado correctamente"))
            return HttpResponseRedirect(reverse_lazy('jobboard:my-list'))
        else:
            ctx = {'form': form}
            messages.error(request, _("Verifique la información enviada"))
            return render(request, self.template_name, ctx)


class JobDeleteView(LoginRequiredMixin, View):

    def get(self, request, job_id):
        job = get_object_or_404(Job, id=job_id, created_by=request.user)
        job.delete()
        messages.success(request, _("Eliminado correctamente"))
        return HttpResponseRedirect(reverse_lazy('jobboard:my-list'))

pythonizame/apps/jobboard/templates/base_jobboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Empleos{% endblock title %}</title>
</head>
<body>
{% block content %}
{% endblock content %}
</body>
</html>

pythonizame/apps/jobboard/templates/jobboard_list.html
{% extends 'base_blog.html' %}
{% block skin %}skin-green{% endblock %}
{% block title %}Jobs {% endblock title %}
{% load static i18n %}



{% block custom_aside_main %}

    {% include 'includes/buttonsJob.html' with add_job=True %}
    <br>
    <div class="col-xs-12 no-padding" style="padding:0;overflow-x:hidden ">
        {% include 'includes/fb_widget.html' %}
    </div>

    <div class="col-xs-12 aside-item" style="padding:0;overflow-x:hidden ">
        <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- index_blog -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:300px;height:250px"
             data-ad-client="ca-pub-5267377707713164"
             data-ad-slot="7659361247"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>


{% endblock custom_aside_main %}

{% block main-swipe %}
    <div class="col-xs-12">
        <!-- Search Form -->
        <div class="col-md-6 col-md-offset-3">

            <!-- Search Form -->
            <form role="form" action="." method="get">
                <!-- Search Field -->
                <div class="row">
                    <h1 class="text-center">Buscar empleo</h1>
                    <div class="form-group">
                        <div class="input-group">
                            <input class="form-control" type="text" value="{% if q %}{{ q }}{% endif %}"
                                   id="txtsearchJobs" name="q" placeholder="Buscar empleo..."/>
                            <span class="input-group-btn">
                                <button class="btn btn-success btn-flat" type="submit" id="btnFindJob">
                                    <span class="fa fa-search">Buscar</span>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="row">

                    <div class="form-group col-md-8 col-xs-12">
                        <label class="checkbox-inline">
                            <input type="checkbox" {% if partial == '1' %} checked {% endif %} name="partial"
                                   id="check_tiempo_parcial" value="1"> Tiempo parcial
                        </label>
                        <label class="checkbox-inline">
                            <input type="checkbox" {% if full == '1' %} checked {% endif %} name="full"
                                   id="check_tiempo_completo" value="1"> Tiempo completo
                        </label>
                    </div>

                    <div class="form-group col-md-4 col-xs-12">
                        <select class="form-control input-sm" name="country" id="countries">
                            <option value="">{% trans 'Selecciona tu país' %}</option>
                            {% for country in countries %}
                                {% if country.0 in available_countries %}
                                    <option value="{{ country.0 }}"
                                            {% if country.0 == selected_country %}selected{% endif %}>{{ country.1 }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>

                </div>

            </form>
            <!-- End of Search Form -->

        </div>
        <br>
        <!-- End of Search Form -->
    </div>




{% endblock main-swipe %}
{% block content %}
    <br>
    {% if object_list %}
        {% for element in object_list %}
            <div class="col-xs-12">
                <div class="box box-widget">
                    <div class="box-body">

                        <div class="col-sm-12 col-xs-12">
                            <div>
                                <h2><a href="{% url 'jobboard:detail' element.id %}">{{ element.title }}</a>
                                <img style="margin-left: 5px;" src="{{ element.country.flag }}">
                                </h2>
                            </div>
                            <hr>
                            <p>{{ element.description |linebreaks|truncatechars:300 }}</p>
                            {% if element.website %}
                                <p><i class="fa fa-globe"></i> <a href="{{ element.website }}">{{ element.website }}</a>
                                </p>
                            {% endif %}
                            <p>
                                <i class="fa fa-building"></i> {{ element.company_name }}
                                <span class="pull-right"
                                      style="font-size: 10px !important;">{{ element.approval_datetime.date }}</span>
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <!-- Paginación de elementos -->
    <div class="row" style="margin-bottom: 20px">
    <div class="col-xs-12">
        <section id="navigationBlog" class="col-xs-12">
            {% if page_obj.has_next %}
                <a href="{% url 'jobboard:list' %}?page={{ page_obj.next_page_number }}{% if q %}&q={{ q }}{% endif %}{% if selected_country %}&country={{ selected_country }}{% endif %}{% if full %}&full={{ full }}{% endif %}{% if partial %}&partial={{ partial }}{% endif %}"
                   class="btn btn-primary pull-left">
                    <i class="fa fa-arrow-circle-left"></i> {% trans 'Anteriores' %} </a>
            {% endif %}
            {% if page_obj.has_previous %}
                <a href="{% url 'jobboard:list' %}?page={{ page_obj.previous_page_number }}{% if q %}&q={{ q }}{% endif %}{% if selected_country %}&country={{ selected_country }}{% endif %}{% if full %}&full={{ full }}{% endif %}{% if partial %}&partial={{ partial }}{% endif %}"
                   class="btn btn-primary pull-right"> {% trans 'Recientes' %}
                    <i class="fa fa-arrow-circle-right"></i>
                </a>
            {% endif %}
        </section>
    </div>
    </div><!-- END Paginación de elementos -->
    {% else %}
        <hr>
        <div class="col-xs-12">
            <div class="panel">
                <h2 class="text-center text-muted">
                    <i class="fa fa-smile-o fa-4x"></i>
                    <br>
                    {% trans 'No hemos encontrado empleos en tu búsqueda' %}
                </h2>


                {% if user.is_authenticated %}
                    <a href="{% url 'jobboard:add' %}">
                        <h4 class="text-center">
                            {% trans '¿Necesitas reclutar a los mejores del mundo?' %}
                        </h4>
                    </a>
                {% else %}

                    <a href="#" data-toggle="modal" data-target="#modalJob">
                        <h4 class="text-center">
                            {% trans '¿Necesitas reclutar a los mejores del mundo?' %}

                        </h4>

                    </a>

                {% endif %}

            </div>
        </div>
    {% endif %}
    <div class="clearfix"></div>
{% endblock content %}
{% block scripts %}
    <script>
        $(document).on('ready', function () {
            pythonizame.jobs_list();
        });
    </script>
{% endblock scripts %}

pythonizame/apps/jobboard/templates/jobboard_my_list.html
{% extends 'base_blog.html' %}
{% block skin %}skin-green{% endblock %}
{% block title %}Jobs {% endblock title %}
{% load static i18n %}



{% block custom_aside_main %}


    {% include 'includes/buttonsJob.html' with add_job=True %}


    <div class="col-xs-12 no-padding" style="padding:0;overflow-x:hidden ">
        {% include 'includes/fb_widget.html' %}
    </div>


       <div class="col-xs-12 aside-item" style="padding:0;overflow-x:hidden ">
        <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- index_blog -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:300px;height:250px"
             data-ad-client="ca-pub-5267377707713164"
             data-ad-slot="7659361247"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>

{% endblock custom_aside_main %}

{% block main-swipe %}
{% endblock main-swipe %}
{% block content %}
    <div class="col-xs-12">
        <div class="box box-widget">
            <div class="box-body">
                <h3>{% trans 'Mis empleos' %}</h3>
                <hr>
                {% if object_list %}
                <table class="table">
                    <thead>
                    <tr>
                        <th width="15%">{% trans 'Fecha' %}</th>
                        <th>{% trans 'Título' %}</th>
                        <th width="15%">{% trans 'Visualizaciones' %}</th>
                        <th width="15%">{% trans 'Estatus' %}</th>
                        <th width="15%">{% trans '' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for element in object_list %}
                        <tr>
                            <td>{{ element.timestamp|date:"d-m-Y" }}</td>
                            <td>{{ element.title }}</td>
                            <td>{{ element.num_of_views }}</td>
                            <td>
                                {% if element.status == 0 %}
                                    Rechazado
                                {% elif element.status == 1 %}
                                    Autorizado
                                {% elif element.status == 2 %}
                                    Borrador
                                {% elif element.status == 3 %}
                                    En Revisión
                                {% endif %}
                            </td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-success btn-flat btn-sm">{% trans 'Acciones' %}</button>
                                    <button type="button" class="btn btn-success btn-flat btn-sm dropdown-toggle"
                                            data-toggle="dropdown" aria-expanded="false">
                                        <span class="caret"></span>
                                        <span class="sr-only">Toggle Dropdown</span>
                                    </button>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="{% url 'jobboard:edit' element.id %}">{% trans 'Editar' %}</a></li>
                                        {% if element.status == 0 or element.status == 2 %}
                                        <li><a href="#" class="revision_job" data-url="{% url 'jobboard:change-to-review' element.id %}" data-toggle="modal" data-target="#modalSendRevision" >{% trans 'Enviar a revisión' %}</a></li>
                                        {% endif %}
                                        <li class="divider"></li>
                                        <li><a href="#" class="delete_job" data-url="{% url 'jobboard:delete' element.id %}" data-toggle="modal" data-target="#modalDeleteJob">{% trans 'Eliminar' %}</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                    <!-- Paginación de elementos -->
                    <div class="row" style="margin-bottom: 20px; margin-top: 20px">
                        <div class="col-xs-12">
                            <section id="navigationBlog" class="col-xs-12">
                                {% if page_obj.has_next %}
                                    <a href="{% url 'jobboard:my-list' %}?page={{ page_obj.next_page_number }}"
                                       class="btn btn-primary pull-left">
                                        <i class="fa fa-arrow-circle-left"></i> {% trans 'Anteriores' %} </a>
                                {% endif %}
                                {% if page_obj.has_previous %}
                                    <a href="{% url 'jobboard:my-list' %}?page={{ page_obj.previous_page_number }}"
                                       class="btn btn-primary pull-right"> {% trans 'Recientes' %}
                                        <i class="fa fa-arrow-circle-right"></i>
                                    </a>
                                {% endif %}
                            </section>
                        </div>
                    </div><!-- END Paginación de elementos -->
                 {% else %}
                    <p class="text-center text-muted">
                         <i class="fa fa-frown-o fa-4x"></i>
                        <br>
                        <b>{% trans 'Aun no cuentas con Jobs registrados' %}</b>
                    </p>
                {% endif %}
            </div>
        </div>
    </div>


    <div class="modal fade" id="modalDeleteJob" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body text-center">
                <p class="lead text-center">{% trans '¿Estas seguro de eliminar tu job?' %}</p>
                <p class="text-center">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-flat btn-lg">{% trans 'Cancelar' %}</button>
                    <a href="" id="btnDeleteJob" class="btn btn-primary btn-flat btn-lg">{% trans 'Aceptar' %}</a>
                </p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



    <div class="modal fade" id="modalSendRevision" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body text-center">
                <p class="lead text-center">{% trans '¿Estas seguro de mandar a revisión tu job?' %}</p>
                <p class="text-center">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-flat btn-lg">{% trans 'Cancelar' %}</button>
                    <a href="" id="btnRevJob" class="btn btn-primary btn-flat btn-lg">{% trans 'Aceptar' %}</a>
                </p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock content %}

{% block scripts %}
    <script>
        $(document).on('ready',function(){
           pythonizame.jobs_mylist();
        });
    </script>
{% endblock scripts %}