pythonizame/apps/account/urls.py
from django.conf.urls import url, include
from pythonizame.apps.account.views import ProfileView, ProfileEditView, ChangePasswordView


app_name = "account"


urlpatterns = [
    url(r'^ws/', include('pythonizame.apps.account.webservices.urls')),
]

urlpatterns += [
    url(r'change/password/$', ChangePasswordView.as_view(), name="change_password"),
    url(r'^(?P<user_id>\w+)/$', ProfileView.as_view(), name="profile"),
    url(r'^(?P<user_id>\w+)/edit/$', ProfileEditView.as_view(), name="profile_edit"),
]

pythonizame/apps/blog/urls.py
from django.conf.urls import url, include

from .feeds import LatestEntriesFeed
from pythonizame.apps.blog.views import (PostDetailView,
                                         IndexView,
                                         PreviewPostDetailView,
                                         PostNew,
                                         ByCategoryView,
                                         ByTagView,
                                         ByAuthorView)


app_name = "blog"

urlpatterns = [
    url(r'^ws/', include('pythonizame.apps.blog.webservices.urls'))
]

urlpatterns += [
    url(r'^$', (IndexView.as_view()), name="index"),
    url(r'^blog/rss/$', LatestEntriesFeed()),
    url(r'^post/new/$', (PostNew.as_view()), name='new_post'),
    url(r'^author/([-_\w]+)/$', (ByAuthorView.as_view()), name='by_author'),
    url(r'^author/([-_\w]+)/page/([0-9]+)/$', ByAuthorView.as_view(), name='by_author_paginated'),
    url(r'^category/([-_\w]+)/$', ByCategoryView.as_view(), name='by_category'),
    url(r'^category/([-_\w]+)/page/([0-9]+)/$', ByCategoryView.as_view(),
        name='by_category_paginated'),
    url(r'^tag/([-_\w]+)/$', ByTagView.as_view(), name='by_tag'),
    url(r'^tag/([-_\w]+)/page/([0-9]+)/$', ByTagView.as_view(), name='by_tag_paginated'),
    url(r'^(?P<slug>[-_\w]+)/$', (PostDetailView.as_view()), name='post_detail'),
    url(r'^(?P<slug>[-_\w]+)/preview/$', PreviewPostDetailView.as_view(), name='post_preview'),
]

pythonizame/apps/blog/webservices/urls.py
from django.conf.urls import url
from pythonizame.apps.blog.webservices.views import AddPostLike, AddPostFavorite

app_name = "ws"

urlpatterns = [
    url(r'add/like/$', AddPostLike.as_view(), name='add_like'),
    url(r'add/favorite/$', AddPostFavorite.as_view(), name='add_favorite'),
]

pythonizame/urls.py
from django.conf.urls import include, url
from django.contrib.flatpages import views
from django.contrib import admin
from django.conf.urls.static import static
from pythonizame.core.json_settings import json_settings

settings = json_settings()

urlpatterns = [
    url(r'^pymin/', include(admin.site.urls)),
    url(r'^videos/', include('pythonizame.apps.videos.urls', namespace='videos')),
    url(r'^', include('pythonizame.apps.books.urls', namespace='books')),
    url(r'^', include('pythonizame.apps.blog.urls', namespace='blog')),
    url(r'^account/', include('pythonizame.apps.account.urls', namespace='account')),
    url(r'^security/', include('pythonizame.apps.security.urls', namespace='security')),
    url(r'^jobboard/', include('pythonizame.apps.jobboard.urls', namespace='jobboard')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if not settings['AMAZON']['S3']['USE_S3']:
    from pythonizame import settings as setts
    urlpatterns += static(setts.MEDIA_URL, document_root=setts.MEDIA_ROOT)


urlpatterns += [
    url(r'^(?P<url>.*/)$', views.flatpage),
]

pythonizame/apps/blog/views.py
import sys
import logging

from slugify import slugify

from django.http import Http404
from django.shortcuts import render
from django.utils import timezone
from django.contrib import messages
from django.core.cache import cache
from django.contrib.auth.models import User
from django.views.generic.detail import DetailView
from django.views.generic import ListView, View

from pythonizame.apps.mixin import LoginRequiredMixin
from pythonizame.apps.account.functions import CheckAchievements
from pythonizame.apps.global_functions import format_sys_errors
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Category, TagPost
from .functions import blog_search
from .forms import PostForm

# ==========================
# Blog by Entries
# ==========================

# Iniciamos el logger para estas vistas
logger = logging.getLogger(__name__)


class PostNew(LoginRequiredMixin, View):
    template_name = "post_new.html"
    form = PostForm

    def get(self, request):
        ctx = {'categories': Category.objects.all(),
               'tags': TagPost.objects.all(), 'form': self.form}
        return render(request, self.template_name, ctx)

    def post(self, request):
        form = self.form(request.POST, request.FILES)
        if form.is_valid():
            try:
                tags = TagPost.objects.filter(id__in=request.POST.getlist('post_tags'))
            except:
                tags = None
            try:
                new_post = form.save(commit=False)
                new_post.author = request.user
                new_post.slug = slugify(new_post.title)
                new_post.save()
                if tags:
                    for tag in tags:
                        new_post.tags.add(tag)
                new_post.save()
                messages.success(request, "Gracias por generar una excelente publicación para la comunidad!")
            except:
                mensaje = format_sys_errors(sys, with_traceback=True)
                logger.error(mensaje)
                messages.error(request, "Ups! algo salió mal, por favor intenta de nuevo")
        else:
            messages.error(request, "Error en los datos recibidos")
        ctx = {'categories': Category.objects.all(),
               'tags': TagPost.objects.all(), 'form': form}
        return render(request, self.template_name, ctx)


class IndexView(View):
    template_name = "index_blog.html"

    @staticmethod
    def get_recent_post():
        """
        Obtenemos las últimas 5 publicaciones
        :return:
        """
        cache_blog_recent_post = cache.get('pythonizame_blog_recent_post')
        if cache_blog_recent_post:
            queryset = cache_blog_recent_post
        else:
            queryset = Post.objects.filter(published=True).order_by('-publication_date')[:5]
            cache.set('pythonizame_blog_recent_post', queryset, 60 * 5)
        return queryset

    def get(self, request):
        """
        Devolvemos consulta de publicaciones al usuario
        """
        if 'q' in request.GET and request.GET['q']:
            search_words = request.GET['q']
            queryset = blog_search(search_words)
        else:
            search_words = ""
            queryset = Post.objects.filter(published=True).order_by('-publication_date')
        paginator = Paginator(queryset, 18)  # 18 elementos
        if 'page' in request.GET and request.GET['page']:
            my_page = int(request.GET['page'])
        else:
            my_page = 1
        try:
            object_list = paginator.page(my_page)
        except PageNotAnInteger:
            object_list = paginator.page(1)
        except EmptyPage:
            object_list = paginator.page(paginator.num_pages)
        # ============================================================
        # Revisamos si tiene medallas pendientes.
        # ============================================================
        if self.request.user.is_authenticated():
            logros = CheckAchievements(self.request.user)
            logros_pendientes = logros.get_all_pending_achievements()
            if logros_pendientes:
                for logro in logros_pendientes:
                    logro.viewed = True
                    logro.date_received = timezone.now().date()
                    logro.save()
        else:
            logros_pendientes = None
        ctx = {'object_list': object_list,
               'pending_achievements': logros_pendientes,
               'recent_post': self.get_recent_post(),
               'page_obj': object_list,
               'queryset': search_words,
               'categories': Category.objects.all()}
        return render(request, self.template_name, ctx)


class PostDetailView(DetailView):
    template_name = "post_detail.html"
    model = Post

    def get_object(self, queryset=None):
        obj = super(PostDetailView, self).get_object(queryset)
        if obj.published:  # Solo se muestra si está publicado
            return obj
        else:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        actual_post = context['post']  # Post consultado
        # Obtenemos los post relacionados
        cache_categories = cache.get('pythonizame_post_categories')
        if cache_categories:
            queryset = cache_categories
        else:
            queryset = Category.objects.all()
            cache.set('pythonizame_post_categories', queryset, 60 * 5)  # Cache por 15 mins
        context['categories'] = queryset
        context['i_like'] = actual_post.i_like(self.request.user)
        context['i_favorite'] = actual_post.i_favorite(self.request.user)
        related_posts = Post.objects.filter(published=True,
                                            categories__in=actual_post.categories.all()
                                            ).exclude(id=actual_post.id).distinct().order_by('?')[:5]
        context['related_posts'] = related_posts
        return context


class PreviewPostDetailView(DetailView):
    """
    Vista previa del usuario author de la publicación
    """
    template_name = "post_detail.html"
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PreviewPostDetailView, self).get_context_data(**kwargs)
        actual_post = context['post']  # Post consultado
        # Obtenemos los post relacionados
        if self.request.user == actual_post.author or self.request.user.is_superuser:
            cache_categories = cache.get('pythonizame_post_categories')
            if cache_categories:
                context['categories'] = cache_categories
            else:
                context['categories'] = Category.objects.all()
                cache.set('pythonizame_post_categories', 60 * 5)  # Cache por 15 mins
            context['i_like'] = actual_post.i_like(self.request.user)
            context['i_favorite'] = actual_post.i_favorite(self.request.user)
            if actual_post.tags.all():
                related_posts = Post.objects.filter(published=True,
                                                    categories=actual_post.categories.all(),
                                                    ).exclude(id=actual_post.id).distinct().order_by('?')[:5]
            else:
                related_posts = Post.objects.filter(published=True,
                                                    categories=actual_post.categories.all()
                                                    ).exclude(id=actual_post.id).distinct().order_by('?')[:5]
            context['related_posts'] = related_posts
            return context
        else:
            raise Http404()


#
# Blog by Author.
#


class ByAuthorView(ListView):
    template_name = 'by_author_blog.html'
    model = Post
    paginate_by = 24

    def get_context_data(self, **kwargs):
        context = super(ByAuthorView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        try:
            # Si envían el número de página entonces lo realizamos
            context['author'] = self.author
            paginator = context['paginator']
            page_obj = paginator.page(self.args[1])
            context['page_obj'] = page_obj
            context['object_list'] = page_obj.object_list
        except:
            pass
        context['recent_post'] = Post.objects.filter(published=True, created_by=self.author).order_by('?')[:5]
        return context

    def get_queryset(self):
        try:
            self.author = User.objects.get(username=self.args[0])
        except:
            self.author = None
        if self.author:
            publicaciones = Post.objects.filter(published=True, created_by=self.author).order_by('-timestamp')
            return publicaciones
        else:
            raise Http404()


# ==========================
# Blog by Category
# ==========================


class ByCategoryView(ListView):
    template_name = 'by_category_blog.html'
    model = Post
    paginate_by = 24

    def get_context_data(self, **kwargs):
        context = super(ByCategoryView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        try:
            # Si envían el número de página entonces lo realizamos
            context['category'] = self.category
            paginator = context['paginator']
            page_obj = paginator.page(self.args[1])
            context['page_obj'] = page_obj
            context['object_list'] = page_obj.object_list
        except:
            pass
        context['recent_post'] = Post.objects.filter(published=True, categories=self.category).order_by('?')[:5]
        return context

    def get_queryset(self):
        try:
            self.category = Category.objects.get(slug=self.args[0])
        except:
            self.category = None
        if self.category:

pythonizame/apps/blog/webservices/views.py
# -*- coding: utf-8 -*-
__author__ = 'alex'
import sys
import logging

from django.views.generic import View
from django.http import JsonResponse
from django.shortcuts import render
from django.db import IntegrityError

from pythonizame.apps.mixin import LoginRequiredMixin
from pythonizame.apps.blog.forms import LikeForm, FavoriteForm
from pythonizame.apps.blog.models import LikePost, FavoritePost
from pythonizame.apps.global_functions import create_json_response
from pythonizame.apps.messages_levels import MSG_SUCCESS, MSG_ERROR
from pythonizame.apps.global_functions import format_sys_errors


# Iniciamos el logger para estas vistas
logger = logging.getLogger(__name__)


class AddPostLike(LoginRequiredMixin, View):
    template_name = 'webservices/add_post_like.html'

    def get(self, request):
        form = LikeForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    @staticmethod
    def post(request):
        form = LikeForm(request.POST)
        is_like = False
        if form.is_valid():
            try:
                new_like = form.save(commit=False)
                new_like.created_by = request.user
                new_like.save()
                mensaje = "Like generado correctamente"
                msg_level = MSG_SUCCESS
                is_like = True
            except IntegrityError:
                try:
                    my_like = LikePost.objects.get(post=form.cleaned_data['post'], created_by=request.user)
                    my_like.delete()
                    mensaje = "Se ha eliminado tu like"
                    msg_level = MSG_SUCCESS
                except LikePost.DoesNotExist:
                    msg_level = MSG_ERROR
                    mensaje = "Error al intentar eliminar el like"
            except:
                msg_level = MSG_ERROR
                mensaje = format_sys_errors(sys, with_traceback=True)
        else:
            mensaje = "Error en los datos recibidos"
            msg_level = MSG_ERROR
        try:
            num_likes = LikePost.objects.filter(post__id=request.POST['post']).count()
        except:
            num_likes = 0
        data = create_json_response(message=mensaje, message_level=msg_level, is_like=is_like, num_likes=num_likes)
        return JsonResponse(data, safe=True)


class AddPostFavorite(LoginRequiredMixin, View):
    template_name = 'webservices/add_post_like.html'

    def get(self, request):
        form = FavoriteForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    @staticmethod
    def post(request):
        form = FavoriteForm(request.POST)
        is_favorite = False
        if form.is_valid():
            try:
                new_fav = form.save(commit=False)
                new_fav.created_by = request.user
                new_fav.save()
                mensaje = "Favorito generado correctamente"
                msg_level = MSG_SUCCESS
                is_favorite = True
            except IntegrityError:
                try:
                    new_fav = FavoritePost.objects.get(post=form.cleaned_data['post'], created_by=request.user)
                    new_fav.delete()
                    mensaje = "Se ha eliminado de tus favoritos"
                    msg_level = MSG_SUCCESS
                except LikePost.DoesNotExist:
                    msg_level = MSG_ERROR
                    mensaje = "Error al intentar eliminar de tus favoritos"
            except:
                msg_level = MSG_ERROR
                mensaje = format_sys_errors(sys, with_traceback=True)
        else:
            mensaje = "Error en los datos recibidos"
            msg_level = MSG_ERROR
        data = create_json_response(message=mensaje, message_level=msg_level, is_favorite=is_favorite)
        return JsonResponse(data, safe=True)

pythonizame/apps/blog/templates/by_author_blog.html
{% extends 'base_blog.html' %}
{% load static %}
{% load thumbnail %}
{% block title %} Blog {% endblock title %}
{% block entry_list %}
    <h1>{{ category.name|capfirst }}</h1><br>
    {% for post in object_list %}
        <article class="post">
                <div class="post-thumb">
                    <a href="{% url 'blog:post_detail' post.slug %}"><img class="img-responsive" src="{{ post.pin_image_thumbnail }}" alt="" /></a>
                </div><!--//post-thumb-->
                <div class="content">
                    <h3 class="post-title"><a href="{% url 'blog:post_detail' post.slug %}">{{ post.title|capfirst }} {{ author.username }}</a></h3>
                    <div class="meta">
                        <ul class="meta-list list-inline">
                            <li class="post-time post_date date updated">{{ post.timestamp }}</li>
                            <li class="post-author"> by <a href="#">@{{ post.created_by.username }}</a></li>
                            <li class="post-comments-link">
                                <a href="blog-single.html#comment-area"><i class="fa fa-heart"></i>{{ post.likes.count }} Likes</a>
                            </li>
                        </ul><!--//meta-list-->
                    </div><!--meta-->
                    <div class="post-entry">
                    <p>{{ post.abstract }}</p>
                    <a class="read-more" href="{% url 'blog:post_detail' post.slug %}">Leer más<i class="fa fa-long-arrow-right"></i></a>
                    </div>
                </div>
        </article><!--//post-->
    {% endfor %}
{% endblock entry_list %}
{% block pagination %}
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="enabled"><a href="{% url 'blog:by_author_paginated' category.slug page_obj.previous_page_number %}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><a href="#">&laquo;</a></li>
            {% endif %}
            {% for num_page in paginator.page_range %}
                {# Solo mostramos +5 y -5 en el paginator #}
                {% if page_obj.number|add:'-5' <= num_page and page_obj.number|add:"5" >= num_page%}
                    {%if page_obj.number == num_page %}
                        <li class="active"><a href="#">{{ num_page }}<span class="sr-only">(current)</span></a></li>
                    {% else %}
                        <li><a href="{% url 'blog:by_author_paginated' author.username num_page %}">{{ num_page }}<span class="sr-only">(current)</span></a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="{% url 'blog:by_author_paginated' author.username page_obj.next_page_number %}">&raquo;</a></li>
            {% else %}
                <li><a href="#" class="disabled">&raquo;</a></li>
            {% endif %}
        </ul><!--//pagination-->
    {% endif %}
{% endblock pagination %}

pythonizame/apps/blog/templates/post_detail.html
{% extends 'base_blog.html' %}
{% load static thumbnail %}
{% block title %} {{ post.title }}{% endblock title %}
{% block metas %}
    <meta name="description" content="{{ post.abstract }}">
    <meta name="keywords" itemprop="keywords" content="{% for my_tag in post.tags.all %}{{ my_tag }},{% endfor %}">
    <meta property="og:locale" content="es_MX"/>
    <meta property="og:type" content="article"/>
    <meta property="og:image" content="{{ post.main_image_thumbnail }}">
    <meta property="og:title" content="{{ post.title }}"/>
    <meta property="og:description" content="{{ post.abstract }}"/>
    <meta property="og:url" content="{{ post.url }}"/>
    <meta property="og:site_name" content="Pythonízame | {{ post.title }}"/>
{% endblock metas %}

{% block content %}
    <article class="col-xs-12" id="detail_article">
        <div id="post_img" style="background: url({{ post.main_image_thumbnail }})">
            <h1 class="tituloDetail">{{ post.title | capfirst }}</h1>
            {% if post.author_image %}
                <span class="author_image"><a href="{{ post.author_link }}" target="_blank">imagen
                    / {{ post.author_image }}</a></span>
            {% endif %}
            {#            <img class="img-responsive" src="{{ post.main_image_thumbnail }}" alt="{{ post.title }}">#}
        </div>
        <div class="actions-detail col-xs-12 text-right">
            <span>
            <a href="https://twitter.com/share" class="twitter-share-button" data-text="{{ post.title }}"
               data-hashtags="pythonizame">Tweet</a>
            </span>&nbsp&nbsp
            <span>
        <!-- Inserta esta etiqueta donde quieras que aparezca Botón Compartir. -->
        <div class="g-plus" data-action="share" data-annotation="bubble" data-href="{{ post.url }}"></div>
            </span>
            <span>{{ post.publication_date | date }}</span>&nbsp&nbsp
            <span class="post_like" data-id="{{ post.id }}"> <i
                    class="{% if i_like %} fa fa-heart postLike {% else %}fa fa-heart-o {% endif %}heart{{ post.id }}"></i> <small
                    class="num_likes{{ post.id }}">{{ post.num_likes }}</small></span>&nbsp&nbsp
            <span data-toggle="tooltip" data-placement="bottom" title="Quitar/Agregar de mis favoritos"
                  class="post_favorite" data-id="{{ post.id }}"> <i
                    class="{% if i_favorite %} fa fa-star postfavorite {% else %}fa fa-star {% endif %}favorite{{ post.id }}"></i></span>
        </div>
        <div class="hr col-xs-5" style="float: right"></div>

        <div class="post_content col-xs-12">
            <div class="banner_post_detailt" style="margin-bottom: 30px">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- post_detalle1 -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-5267377707713164"
                     data-ad-slot="5925055247"
                     data-ad-format="auto"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
            {{ post.content|safe }}
            <br/><br/>
            <div class="banner_post_detailt">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- Primera página - 3 (pythoniza.me) -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-5267377707713164"
                     data-ad-slot="9762554440"
                     data-ad-format="auto"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
            <div id="disqus_thread"></div>
        </div>

    </article>
{% endblock content %}
{% block aside_blog %}
    <div class="col-xs-12 no-padding">
        <div class="box box-primary">
            <div class="box-body box-profile">
                {% if post.author.userprofile.image %}
{#                    <a href="{% url 'account:profile' post.author.id %} ">#}
                        <img
                            src="{{ post.author.userprofile.avatar }}"
                            class="profile-user-img img-responsive img-circle"
                            alt=""
                            height="50px"/>
{#                    </a>#}
                {% else %}
{#                    <a href="{% url 'account:profile' post.author.id %} ">#}
                        <img src="{% static 'app/img/default.gif' %}"
                                                                               class="profile-user-img img-responsive img-circle"
                                                                               alt=""
                                                                               height="50px"/>
{#                    </a>#}
                {% endif %}


                <h3 class="profile-username text-center">{{ post.author.first_name }} {{ post.author.last_name }}</h3>

                <p class="text-muted text-center">{{ post.author.userprofile.about_me }}</p>
            </div>
            <!-- /.box-body -->
        </div>
    </div>



    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">Etiquetas</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                {% for my_tag in post.tags.all %}
                    <small class="fa fa-tag"><a href="{% url 'blog:by_tag' my_tag.slug %}"> {{ my_tag }}</a></small>
                {% endfor %}
                <!-- /.users-list -->
            </div>
            <!-- /.box-body -->
        </div>

    </div>




    <div class="col-lg-12 col-md-12 col-sm-6 col-xs-12 no-padding ">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Temas relacionados</h3>

            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <ul class="products-list product-list-in-box">

                    {% for post_rel in related_posts %}
                        <li class="item">
                            <div class="product-img">
                                <img src="{{ post_rel.related_post_image_thumbnail }}" alt="{{ post_rel.title }}">
                            </div>
                            <div class="product-info">
                                <a href="{% url 'blog:post_detail' post_rel.slug %}"
                                   class="product-title">{{ post_rel.title }}
                                </a>
                        <span class="product-description">
                          Hace {{ post_rel.publication_date|timesince }}
                        </span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <!-- /.box-body -->
        </div>
    </div>
    <div class="col-xs-12 aside-item" style="padding:0;overflow-x:hidden ">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- index_blog -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:300px;height:250px"
             data-ad-client="ca-pub-5267377707713164"
             data-ad-slot="7659361247"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
{% endblock aside_blog %}
{% block scripts %}
    {% if config.enable_disqus %}
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES * * */
            var disqus_shortname = '{{ config.disqus_shortname }}';

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function () {
                var dsq = document.createElement('script');
                dsq.type = 'text/javascript';
                dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments
            powered by Disqus.</a></noscript>
    {% endif %}
{% endblock scripts %}