pythonizame/apps/account/urls.py
from django.conf.urls import url, include
from pythonizame.apps.account.views import ProfileView, ProfileEditView, ChangePasswordView


app_name = "account"


urlpatterns = [
    url(r'^ws/', include('pythonizame.apps.account.webservices.urls')),
]

urlpatterns += [
    url(r'change/password/$', ChangePasswordView.as_view(), name="change_password"),
    url(r'^(?P<user_id>\w+)/$', ProfileView.as_view(), name="profile"),
    url(r'^(?P<user_id>\w+)/edit/$', ProfileEditView.as_view(), name="profile_edit"),
]

pythonizame/apps/blog/urls.py
from django.conf.urls import url, include

from .feeds import LatestEntriesFeed
from pythonizame.apps.blog.views import (PostDetailView,
                                         IndexView,
                                         PreviewPostDetailView,
                                         PostNew,
                                         ByCategoryView,
                                         ByTagView,
                                         ByAuthorView)


app_name = "blog"

urlpatterns = [
    url(r'^ws/', include('pythonizame.apps.blog.webservices.urls'))
]

urlpatterns += [
    url(r'^$', (IndexView.as_view()), name="index"),
    url(r'^blog/rss/$', LatestEntriesFeed()),
    url(r'^post/new/$', (PostNew.as_view()), name='new_post'),
    url(r'^author/([-_\w]+)/$', (ByAuthorView.as_view()), name='by_author'),
    url(r'^author/([-_\w]+)/page/([0-9]+)/$', ByAuthorView.as_view(), name='by_author_paginated'),
    url(r'^category/([-_\w]+)/$', ByCategoryView.as_view(), name='by_category'),
    url(r'^category/([-_\w]+)/page/([0-9]+)/$', ByCategoryView.as_view(),
        name='by_category_paginated'),
    url(r'^tag/([-_\w]+)/$', ByTagView.as_view(), name='by_tag'),
    url(r'^tag/([-_\w]+)/page/([0-9]+)/$', ByTagView.as_view(), name='by_tag_paginated'),
    url(r'^(?P<slug>[-_\w]+)/$', (PostDetailView.as_view()), name='post_detail'),
    url(r'^(?P<slug>[-_\w]+)/preview/$', PreviewPostDetailView.as_view(), name='post_preview'),
]

pythonizame/apps/blog/webservices/urls.py
from django.conf.urls import url
from pythonizame.apps.blog.webservices.views import AddPostLike, AddPostFavorite

app_name = "ws"

urlpatterns = [
    url(r'add/like/$', AddPostLike.as_view(), name='add_like'),
    url(r'add/favorite/$', AddPostFavorite.as_view(), name='add_favorite'),
]

pythonizame/apps/security/urls.py
from django.conf.urls import *
from .views import Login, RegisterView, ActivateAccount, RequestNewToken, RecoverPassword, ChangePassword, LogoutView

urlpatterns = [
    url(r'^login/$', Login.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'activation/(?P<token>.*)/$', ActivateAccount.as_view(), name='activation_account'),
    url(r'token/(?P<token>.*)/password/(?P<username>.*)/$', ChangePassword.as_view(), name='change_password'),
    url(r'new/token/activation/$', RequestNewToken.as_view(), name='new_token_activation'),
    url(r'recover/password/$', RecoverPassword.as_view(), name='recover_password'),
]

pythonizame/apps/videos/urls.py
from django.conf.urls import url, include
from pythonizame.apps.videos.views import IndexView, PlayListVideosView, VideoDetailView

app_name = "videos"


urlpatterns = [
    url(r'^$', (IndexView.as_view()), name="list"),
    url(r'^(?P<slug>[-_\w]+)/$', (PlayListVideosView.as_view()), name='playlist-detail'),
    url(r'^video-detail/(?P<pk>[-_\w]+)/$', (VideoDetailView.as_view()), name='video-detail'),
]

pythonizame/urls.py
from django.conf.urls import include, url
from django.contrib.flatpages import views
from django.contrib import admin
from django.conf.urls.static import static
from pythonizame.core.json_settings import json_settings

settings = json_settings()

urlpatterns = [
    url(r'^pymin/', include(admin.site.urls)),
    url(r'^videos/', include('pythonizame.apps.videos.urls', namespace='videos')),
    url(r'^', include('pythonizame.apps.books.urls', namespace='books')),
    url(r'^', include('pythonizame.apps.blog.urls', namespace='blog')),
    url(r'^account/', include('pythonizame.apps.account.urls', namespace='account')),
    url(r'^security/', include('pythonizame.apps.security.urls', namespace='security')),
    url(r'^jobboard/', include('pythonizame.apps.jobboard.urls', namespace='jobboard')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if not settings['AMAZON']['S3']['USE_S3']:
    from pythonizame import settings as setts
    urlpatterns += static(setts.MEDIA_URL, document_root=setts.MEDIA_ROOT)


urlpatterns += [
    url(r'^(?P<url>.*/)$', views.flatpage),
]

pythonizame/apps/blog/forms.py
__author__ = 'alex'

from django import forms
from ckeditor.widgets import CKEditorWidget

from pythonizame.apps.blog.models import LikePost, FavoritePost, Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget)

    class Meta:
        model = Post
        exclude = ['author', 'slug', 'timestamp', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'main_image': forms.FileInput(attrs={'class': 'form-control', 'accept': 'image/*'}),
            'pin_image': forms.FileInput(attrs={'class': 'form-control', 'accept': 'image/*'}),
            'author_image': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': "Nombre del autor, ejemplo 'Gaspar Dzul - Flickr'"}),
            'author_link': forms.URLInput(attrs={'class': 'form-control'}),
            'abstract': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'title': "Título",
            'main_image': "Imagen principal.",
            'pin_image': "Imagen pequeña.",
            'author_image': "Autor de la imagen.",
            'author_link': "Link del autor.",
            'abstract': "Texto de introducción.",
            'content': "Contenido de la publicación",
            'category': "Categoría",
        }
        help_texts = {
            'main_image': "Imagen de portada de la publicación",
            'pin_image': "Imagen que se visualiza en el listado de las publicaciones",
            'author_image': "Se recomienda que el autor de ambas imagenes sea el mismo.",
            'abstract': "Máximo 200 caracteres",
        }


class LikeForm(forms.ModelForm):
    class Meta:
        model = LikePost
        exclude = ['created_by', 'timestamp']


class FavoriteForm(forms.ModelForm):
    class Meta:
        model = FavoritePost
        exclude = ['created_by', 'timestamp']

pythonizame/apps/blog/views.py
import sys
import logging

from slugify import slugify

from django.http import Http404
from django.shortcuts import render
from django.utils import timezone
from django.contrib import messages
from django.core.cache import cache
from django.contrib.auth.models import User
from django.views.generic.detail import DetailView
from django.views.generic import ListView, View

from pythonizame.apps.mixin import LoginRequiredMixin
from pythonizame.apps.account.functions import CheckAchievements
from pythonizame.apps.global_functions import format_sys_errors
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Category, TagPost
from .functions import blog_search
from .forms import PostForm

# ==========================
# Blog by Entries
# ==========================

# Iniciamos el logger para estas vistas
logger = logging.getLogger(__name__)


class PostNew(LoginRequiredMixin, View):
    template_name = "post_new.html"
    form = PostForm

    def get(self, request):
        ctx = {'categories': Category.objects.all(),
               'tags': TagPost.objects.all(), 'form': self.form}
        return render(request, self.template_name, ctx)

    def post(self, request):
        form = self.form(request.POST, request.FILES)
        if form.is_valid():
            try:
                tags = TagPost.objects.filter(id__in=request.POST.getlist('post_tags'))
            except:
                tags = None
            try:
                new_post = form.save(commit=False)
                new_post.author = request.user
                new_post.slug = slugify(new_post.title)
                new_post.save()
                if tags:
                    for tag in tags:
                        new_post.tags.add(tag)
                new_post.save()
                messages.success(request, "Gracias por generar una excelente publicación para la comunidad!")
            except:
                mensaje = format_sys_errors(sys, with_traceback=True)
                logger.error(mensaje)
                messages.error(request, "Ups! algo salió mal, por favor intenta de nuevo")
        else:
            messages.error(request, "Error en los datos recibidos")
        ctx = {'categories': Category.objects.all(),
               'tags': TagPost.objects.all(), 'form': form}
        return render(request, self.template_name, ctx)


class IndexView(View):
    template_name = "index_blog.html"

    @staticmethod
    def get_recent_post():
        """
        Obtenemos las últimas 5 publicaciones
        :return:
        """
        cache_blog_recent_post = cache.get('pythonizame_blog_recent_post')
        if cache_blog_recent_post:
            queryset = cache_blog_recent_post
        else:
            queryset = Post.objects.filter(published=True).order_by('-publication_date')[:5]
            cache.set('pythonizame_blog_recent_post', queryset, 60 * 5)
        return queryset

    def get(self, request):
        """
        Devolvemos consulta de publicaciones al usuario
        """
        if 'q' in request.GET and request.GET['q']:
            search_words = request.GET['q']
            queryset = blog_search(search_words)
        else:
            search_words = ""
            queryset = Post.objects.filter(published=True).order_by('-publication_date')
        paginator = Paginator(queryset, 18)  # 18 elementos
        if 'page' in request.GET and request.GET['page']:
            my_page = int(request.GET['page'])
        else:
            my_page = 1
        try:
            object_list = paginator.page(my_page)
        except PageNotAnInteger:
            object_list = paginator.page(1)
        except EmptyPage:
            object_list = paginator.page(paginator.num_pages)
        # ============================================================
        # Revisamos si tiene medallas pendientes.
        # ============================================================
        if self.request.user.is_authenticated():
            logros = CheckAchievements(self.request.user)
            logros_pendientes = logros.get_all_pending_achievements()
            if logros_pendientes:
                for logro in logros_pendientes:
                    logro.viewed = True
                    logro.date_received = timezone.now().date()
                    logro.save()
        else:
            logros_pendientes = None
        ctx = {'object_list': object_list,
               'pending_achievements': logros_pendientes,
               'recent_post': self.get_recent_post(),
               'page_obj': object_list,
               'queryset': search_words,
               'categories': Category.objects.all()}
        return render(request, self.template_name, ctx)


class PostDetailView(DetailView):
    template_name = "post_detail.html"
    model = Post

    def get_object(self, queryset=None):
        obj = super(PostDetailView, self).get_object(queryset)
        if obj.published:  # Solo se muestra si está publicado
            return obj
        else:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        actual_post = context['post']  # Post consultado
        # Obtenemos los post relacionados
        cache_categories = cache.get('pythonizame_post_categories')
        if cache_categories:
            queryset = cache_categories
        else:
            queryset = Category.objects.all()
            cache.set('pythonizame_post_categories', queryset, 60 * 5)  # Cache por 15 mins
        context['categories'] = queryset
        context['i_like'] = actual_post.i_like(self.request.user)
        context['i_favorite'] = actual_post.i_favorite(self.request.user)
        related_posts = Post.objects.filter(published=True,
                                            categories__in=actual_post.categories.all()
                                            ).exclude(id=actual_post.id).distinct().order_by('?')[:5]
        context['related_posts'] = related_posts
        return context


class PreviewPostDetailView(DetailView):
    """
    Vista previa del usuario author de la publicación
    """
    template_name = "post_detail.html"
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PreviewPostDetailView, self).get_context_data(**kwargs)
        actual_post = context['post']  # Post consultado
        # Obtenemos los post relacionados
        if self.request.user == actual_post.author or self.request.user.is_superuser:
            cache_categories = cache.get('pythonizame_post_categories')
            if cache_categories:
                context['categories'] = cache_categories
            else:
                context['categories'] = Category.objects.all()
                cache.set('pythonizame_post_categories', 60 * 5)  # Cache por 15 mins
            context['i_like'] = actual_post.i_like(self.request.user)
            context['i_favorite'] = actual_post.i_favorite(self.request.user)
            if actual_post.tags.all():
                related_posts = Post.objects.filter(published=True,
                                                    categories=actual_post.categories.all(),
                                                    ).exclude(id=actual_post.id).distinct().order_by('?')[:5]
            else:
                related_posts = Post.objects.filter(published=True,
                                                    categories=actual_post.categories.all()
                                                    ).exclude(id=actual_post.id).distinct().order_by('?')[:5]
            context['related_posts'] = related_posts
            return context
        else:
            raise Http404()


#
# Blog by Author.
#


class ByAuthorView(ListView):
    template_name = 'by_author_blog.html'
    model = Post
    paginate_by = 24

    def get_context_data(self, **kwargs):
        context = super(ByAuthorView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        try:
            # Si envían el número de página entonces lo realizamos
            context['author'] = self.author
            paginator = context['paginator']
            page_obj = paginator.page(self.args[1])
            context['page_obj'] = page_obj
            context['object_list'] = page_obj.object_list
        except:
            pass
        context['recent_post'] = Post.objects.filter(published=True, created_by=self.author).order_by('?')[:5]
        return context

    def get_queryset(self):
        try:
            self.author = User.objects.get(username=self.args[0])
        except:
            self.author = None
        if self.author:
            publicaciones = Post.objects.filter(published=True, created_by=self.author).order_by('-timestamp')
            return publicaciones
        else:
            raise Http404()


# ==========================
# Blog by Category
# ==========================


class ByCategoryView(ListView):
    template_name = 'by_category_blog.html'
    model = Post
    paginate_by = 24

    def get_context_data(self, **kwargs):
        context = super(ByCategoryView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        try:
            # Si envían el número de página entonces lo realizamos
            context['category'] = self.category
            paginator = context['paginator']
            page_obj = paginator.page(self.args[1])
            context['page_obj'] = page_obj
            context['object_list'] = page_obj.object_list
        except:
            pass
        context['recent_post'] = Post.objects.filter(published=True, categories=self.category).order_by('?')[:5]
        return context

    def get_queryset(self):
        try:
            self.category = Category.objects.get(slug=self.args[0])
        except:
            self.category = None
        if self.category:

pythonizame/apps/blog/templates/includes/analitycs.html
 {% if config.google_analytics %}
    <script>
     (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
     m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
     })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

     ga('create', '{{ config.google_analytics }}', 'auto');
     ga('send', 'pageview');

    </script>
{% endif %}

pythonizame/apps/blog/templates/includes/botonTwitterShare.html
<a href="https://twitter.com/share" class="twitter-share-button" data-hashtags="pythonizame">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

pythonizame/apps/blog/templates/includes/div_social.html
<div style="font-size: 30px" class="text-center items-social">
    {% if config.facebook %}
        <a href="{{ config.facebook }}" target="_blank" style="color: #01579B"><i class="fa fa-facebook-f"></i></a>
    {% endif %}
    {% if config.instagram %}
        <a href="{{ config.instagram }}" style="color: #4E342E" target="_blank"><i
                class="fa fa-instagram"></i></a>
    {% endif %}
    {% if config.pinterest %}
        <a href="{{ config.pinterest }}" style="color: red" target="_blank"><i
                class="fa fa-pinterest"></i></a>
    {% endif %}
    {% if config.twitter %}
        <a href="{{ config.twitter }}" target="_blank"><i class="fa fa-twitter"></i></a>
    {% endif %}
    {% if config.gplus %}
        <a href="{{ config.gplus }}" style="color: #F44336" target="_blank"><i
                class="fa fa-google-plus"></i></a>
    {% endif %}
</div>

pythonizame/apps/blog/templates/includes/fb_sdk.html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.5&appId=162208637500000";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

pythonizame/apps/blog/templates/includes/fb_widget.html
<div class="fb-page" data-href="https://www.facebook.com/pythonizame/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/pythonizame/"><a href="https://www.facebook.com/pythonizame/">Pythonízame</a></blockquote></div></div>

pythonizame/apps/blog/templates/includes/footer.html
{#<div id="footer">#}
{#    <div class="container">#}
{#        <div class="row">#}
{#            <h3 class="footertext">About Us:</h3>#}
{#            <br>#}
{#            <div class="col-md-4">#}
{#                    <img src="http://oi60.tinypic.com/w8lycl.jpg" class="img-circle" alt="the-brains">#}
{#                    <br>#}
{#                    <h4 class="footertext">Programmer</h4>#}
{#                    <p class="footertext">You can thank all the crazy programming here to this guy.<br>#}
{#            </div>#}
{#            <div class="col-md-4">#}
{#                    <img src="http://oi60.tinypic.com/2z7enpc.jpg" class="img-circle" alt="...">#}
{#                    <br>#}
{#                    <h4 class="footertext">Artist</h4>#}
{#                    <p class="footertext">All the images here are hand drawn by this man.<br>#}
{#            </div>#}
{#            <div class="col-md-4">#}
{#                    <img src="http://oi61.tinypic.com/307n6ux.jpg" class="img-circle" alt="...">#}
{#                    <br>#}
{#                    <h4 class="footertext">Designer</h4>#}
{#                    <p class="footertext">This pretty site and the copy it holds are all thanks to this guy.<br>#}
{#            </div>#}
{#        </div>#}
{#        <div class="row">#}
{#            <p><a href="#">Contact Stuff Here</a> <p class="footertext">Copyright 2014</p></p>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

pythonizame/apps/blog/templates/includes/metasGenerico.html
{% load staticfiles %}
<meta name="description" content="Noticias sobre el lenguaje de Programación Python">
<meta property="og:locale" content="es_MX" />
<meta property="og:type" content="website" />
<meta property="og:image" content="{% if config.logo %}{{ config.logo.url }}{% endif %}">
<meta property="og:title" content="Pythonízame - Noticias sobre el lenguaje de Programación Python" />
<meta property="og:description" content="Noticias sobre el lenguaje de Programación Python" />
<meta property="og:url" content="http://pythoniza.me" />
<meta property="og:site_name" content="{{ config.site_name }}" />
<meta name="google-site-verification" content="eJiYWi85t4ioSwkb1JFCYBTt0vJXCbKklUtRO6v3ztE" />

pythonizame/apps/blog/templates/includes/navbar_header.html
{% load staticfiles flatpages i18n %}
<header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg">
          <img src="{% if config.logo %}{{ config.logo.url }}{% endif %}" alt="{{ config.site_name }}" class="img-responsive pull-left" style="width: 50px;height: 50px">
              {% block title_header %}{{ config.site_name }}{% endblock title_header %}</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">

          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

              <li><a href="/">Blog</a></li>
              <li><a href="{% url 'books:index' %}">Books</a></li>
              <li><a href="{% url 'jobboard:list' %}">Jobs</a></li>
{#              <li><a href="{% url 'videos:list' %}">Videos</a></li>#}
              {% get_flatpages as flatpages %}
                {% for page in flatpages %}
                    {% if page.flatpage.status == 1 %}
                        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                    {% endif %}
                {% endfor %}
              {% if user.is_authenticated %}
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {% if user.userprofile.avatar %}
                        <img src="{{ user.userprofile.avatar }}" class="user-image" alt="User Image">
                    {% endif %}
                  <span class="hidden-xs">{{ user.first_name }}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                      {% if user.userprofile.avatar %}
                    <img src="{{user.userprofile.avatar }}" class="img-circle" alt="Perfile de usuario">
                          {% endif %}
                    <p>
                      {% if user.first_name %}
                              {{ user.first_name }} {{ user.last_name }}
                          {% else %}
                              @{{ user.username }}
                          {% endif %}

                      <small>{% trans 'Usuario desde' %} {{ user.date_joined.date }}</small>
                    </p>
                  </li>
                  <!-- Menu Body -->
{#                  <li class="user-body">#}
{#                    <div class="col-xs-4 text-center">#}
{#                      <a href="#">Followers</a>#}
{#                    </div>#}
{#                    <div class="col-xs-4 text-center">#}
{#                      <a href="#">Sales</a>#}
{#                    </div>#}
{#                    <div class="col-xs-4 text-center">#}
{#                      <a href="#">Friends</a>#}
{#                    </div>#}
{#                  </li>#}
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="{% url 'account:profile' user.id %}" class="btn btn-default btn-flat">{% trans 'Perfil' %}</a>
                    </div>
                    <div class="pull-right">
                      <a href="{% url 'security:logout' %}" class="btn btn-default btn-flat">{% trans 'Salir' %}</a>
                    </div>
                  </li>
                </ul>
              </li>
             {% else %}
                  <li><a href="{% url 'security:login' %}">{% trans 'Ingresar a' %} Pythonízame</a></li>
             {% endif %}
            </ul>
          </div>
        </nav>
      </header>