pythonizame/apps/account/urls.py
from django.conf.urls import url, include
from pythonizame.apps.account.views import ProfileView, ProfileEditView, ChangePasswordView


app_name = "account"


urlpatterns = [
    url(r'^ws/', include('pythonizame.apps.account.webservices.urls')),
]

urlpatterns += [
    url(r'change/password/$', ChangePasswordView.as_view(), name="change_password"),
    url(r'^(?P<user_id>\w+)/$', ProfileView.as_view(), name="profile"),
    url(r'^(?P<user_id>\w+)/edit/$', ProfileEditView.as_view(), name="profile_edit"),
]

pythonizame/apps/blog/urls.py
from django.conf.urls import url, include

from .feeds import LatestEntriesFeed
from pythonizame.apps.blog.views import (PostDetailView,
                                         IndexView,
                                         PreviewPostDetailView,
                                         PostNew,
                                         ByCategoryView,
                                         ByTagView,
                                         ByAuthorView)


app_name = "blog"

urlpatterns = [
    url(r'^ws/', include('pythonizame.apps.blog.webservices.urls'))
]

urlpatterns += [
    url(r'^$', (IndexView.as_view()), name="index"),
    url(r'^blog/rss/$', LatestEntriesFeed()),
    url(r'^post/new/$', (PostNew.as_view()), name='new_post'),
    url(r'^author/([-_\w]+)/$', (ByAuthorView.as_view()), name='by_author'),
    url(r'^author/([-_\w]+)/page/([0-9]+)/$', ByAuthorView.as_view(), name='by_author_paginated'),
    url(r'^category/([-_\w]+)/$', ByCategoryView.as_view(), name='by_category'),
    url(r'^category/([-_\w]+)/page/([0-9]+)/$', ByCategoryView.as_view(),
        name='by_category_paginated'),
    url(r'^tag/([-_\w]+)/$', ByTagView.as_view(), name='by_tag'),
    url(r'^tag/([-_\w]+)/page/([0-9]+)/$', ByTagView.as_view(), name='by_tag_paginated'),
    url(r'^(?P<slug>[-_\w]+)/$', (PostDetailView.as_view()), name='post_detail'),
    url(r'^(?P<slug>[-_\w]+)/preview/$', PreviewPostDetailView.as_view(), name='post_preview'),
]

pythonizame/apps/videos/urls.py
from django.conf.urls import url, include
from pythonizame.apps.videos.views import IndexView, PlayListVideosView, VideoDetailView

app_name = "videos"


urlpatterns = [
    url(r'^$', (IndexView.as_view()), name="list"),
    url(r'^(?P<slug>[-_\w]+)/$', (PlayListVideosView.as_view()), name='playlist-detail'),
    url(r'^video-detail/(?P<pk>[-_\w]+)/$', (VideoDetailView.as_view()), name='video-detail'),
]

pythonizame/urls.py
from django.conf.urls import include, url
from django.contrib.flatpages import views
from django.contrib import admin
from django.conf.urls.static import static
from pythonizame.core.json_settings import json_settings

settings = json_settings()

urlpatterns = [
    url(r'^pymin/', include(admin.site.urls)),
    url(r'^videos/', include('pythonizame.apps.videos.urls', namespace='videos')),
    url(r'^', include('pythonizame.apps.books.urls', namespace='books')),
    url(r'^', include('pythonizame.apps.blog.urls', namespace='blog')),
    url(r'^account/', include('pythonizame.apps.account.urls', namespace='account')),
    url(r'^security/', include('pythonizame.apps.security.urls', namespace='security')),
    url(r'^jobboard/', include('pythonizame.apps.jobboard.urls', namespace='jobboard')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if not settings['AMAZON']['S3']['USE_S3']:
    from pythonizame import settings as setts
    urlpatterns += static(setts.MEDIA_URL, document_root=setts.MEDIA_ROOT)


urlpatterns += [
    url(r'^(?P<url>.*/)$', views.flatpage),
]

pythonizame/apps/videos/models.py
import os
import uuid
import logging

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.utils import timezone

from ckeditor_uploader.fields import RichTextUploadingField

# Iniciamos el logger para estas vistas
logger = logging.getLogger(__name__)


def image_path_video(self, filename):
    today = timezone.now()
    path = "videos/{0}/{1}/{2}/".format(today.year, today.month, today.day)
    ext = filename.split('.')[-1]
    my_filename = "{0}.{1}".format(str(uuid.uuid1()).replace('-', ''), ext)
    url = os.path.join(path, my_filename)
    return url


class VideoCategory(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Categoría de videos")
        verbose_name_plural = _("Categorías de videos")


class PlayList(models.Model):

    STATUS_LIST = (
        (0, _("No aprobado")),
        (1, _("Aprobado")),
        (2, _("En revisión"))
    )

    title = models.CharField(max_length=500, unique=True)
    slug = models.SlugField(unique=True)
    abstract = models.TextField(max_length=5000)
    description = RichTextUploadingField(max_length=1000000)
    categories = models.ManyToManyField(VideoCategory, help_text=_("Categorías a la que pertenece"))
    cover = models.ImageField(null=True, blank=True, upload_to=image_path_video)
    created_by = models.ForeignKey(User, related_name='created_by')
    author = models.ForeignKey(User, related_name='author')
    status = models.IntegerField(choices=STATUS_LIST, default=2)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta: 
        verbose_name = _("Lista de reproducción")
        verbose_name_plural = _("Listas de reproducción")

    @property
    def url(self):
        return "https://pythoniza.me/{0}".format(self.slug)


class Video(models.Model):
    created_by = models.ForeignKey(User)
    order = models.IntegerField(default=1)
    playlist = models.ForeignKey(PlayList, help_text=_("Lista de reproducción al que pertenece el video"))
    title = models.CharField(max_length=500)
    description = RichTextUploadingField(max_length=1000000)
    youtube_id = models.CharField(max_length=500)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('order', )
        verbose_name = _("Video")
        verbose_name_plural = _("Videos")

pythonizame/apps/videos/views.py
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from slugify import slugify
from django.http import Http404
from django.shortcuts import render
from django.utils import timezone
from django.contrib import messages
from django.core.cache import cache
from django.views.generic import View, DetailView
from .models import PlayList, Video, VideoCategory
from .functions import video_search


class IndexView(View):
    template_name = "video_list.html"

    @staticmethod
    def get_recent_playlist():
        """
        Obtenemos las últimas 5 publicaciones
        :return:
        """
        cache_blog_recent_post = cache.get('pythonizame_recent_playlist')
        if cache_blog_recent_post:
            queryset = cache_blog_recent_post
        else:
            queryset = PlayList.objects.filter(status=1).order_by('-timestamp')[:5]
            cache.set('pythonizame_recent_playlist', queryset, 60 * 5)
        return queryset

    def get(self, request):
        """
        Devolvemos consulta de publicaciones al usuario
        """
        if 'q' in request.GET and request.GET['q']:
            search_words = request.GET['q']
            queryset = video_search(search_words)
        else:
            search_words = ""
            queryset = PlayList.objects.filter(status=1).order_by('-timestamp')
        paginator = Paginator(queryset, 18)  # 18 elementos
        if 'page' in request.GET and request.GET['page']:
            my_page = int(request.GET['page'])
        else:
            my_page = 1
        try:
            object_list = paginator.page(my_page)
        except PageNotAnInteger:
            object_list = paginator.page(1)
        except EmptyPage:
            object_list = paginator.page(paginator.num_pages)
        categories = VideoCategory.objects.all()
        ctx = {'object_list': object_list,
               'categories': categories,
               'page_obj': object_list,
               'recent_playlist': self.get_recent_playlist(),
               'queryset': search_words}
        return render(request, self.template_name, ctx)


class PlayListVideosView(DetailView):
    template_name = "playlist_detail.html"
    model = PlayList

    def get_object(self, queryset=None):
        obj = super(PlayListVideosView, self).get_object(queryset)
        if obj.status == 1:  # Solo se muestra si está autorizada la visualización
            return obj
        else:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super(PlayListVideosView, self).get_context_data(**kwargs)
        actual_playlist = context['playlist']  # Playlist consultado
        # Obtenemos los post relacionados
        cache_categories = cache.get('pythonizame_videos_categories')
        if cache_categories:
            queryset = cache_categories
        else:
            queryset = VideoCategory.objects.all()
            cache.set('pythonizame_video_categories', queryset, 60 * 5)  # Cache por 15 mins
        context['categories'] = queryset
        actual_categories_id = list(actual_playlist.categories.all().values_list('id', flat=True))
        rel_playlist_id = set(list(PlayList.objects.filter(status=1,
                                                           categories__in=actual_categories_id).exclude(
            id=actual_playlist.id).values_list(
            'id', flat=True
        )))
        rel_playlist = PlayList.objects.filter(id__in=rel_playlist_id).order_by('?')[:5]
        context['related_playlist'] = rel_playlist
        return context


class VideoDetailView(DetailView):
    template_name = "video_detail.html"
    model = Video

    # def get_object(self, queryset=None):
    #     obj = super(VideoDetailView, self).get_object(queryset)
    #     if obj.status == 1:  # Solo se muestra si está autorizada la visualización
    #         return obj
    #     else:
    #         raise Http404

    def get_context_data(self, **kwargs):
        context = super(VideoDetailView, self).get_context_data(**kwargs)
        obj_video = context['video']  # Video consultado
        # Obtenemos el video
        # Obtenemos los post relacionados
        # cache_categories = cache.get('pythonizame_videos_categories')
        # if cache_categories:
        #     queryset = cache_categories
        # else:
        #     queryset = VideoCategory.objects.all()
        #     cache.set('pythonizame_video_categories', queryset, 60 * 5)  # Cache por 15 mins
        # context['categories'] = queryset
        # actual_categories_id = list(actual_playlist.categories.all().values_list('id', flat=True))
        # rel_playlist_id = set(list(PlayList.objects.filter(status=1,
        #                                                    categories__in=actual_categories_id).exclude(
        #     id=actual_playlist.id).values_list(
        #     'id', flat=True
        # )))
        # rel_playlist = PlayList.objects.filter(id__in=rel_playlist_id).order_by('?')[:5]
        # context['related_playlist'] = rel_playlist
        return context

pythonizame/apps/videos/templates/playlist_detail.html
{% extends 'base_video.html' %}
{% load static thumbnail i18n %}
{% block title %} {{ playlist.title }}{% endblock title %}
{% block metas %}
    <meta name="description" content="{{ post.abstract }}">
    <meta name="keywords" itemprop="keywords" content="{% for my_tag in post.tags.all %}{{ my_tag }},{% endfor %}">
    <meta property="og:locale" content="es_MX"/>
    <meta property="og:type" content="article"/>
    <meta property="og:image" content="{{ playlist.cover|thumbnail_url:'main_blog_image' }}">
    <meta property="og:title" content="{{ playlist.title }}"/>
    <meta property="og:description" content="{{ playlist.abstract }}"/>
    <meta property="og:url" content="{{ playlist.url }}"/>
    <meta property="og:site_name" content="Pythonízame | {{ playlist.title }}"/>
{% endblock metas %}

{% block content %}
    <article class="col-xs-12" id="detail_article">
        <div id="post_img" style="background: url({{ playlist.cover|thumbnail_url:'main_blog_image' }})">
            <h1 class="tituloDetail">{{ playlist.title | capfirst }}</h1>
                <span class="author_image">{{ playlist.video_set.all.count }} {% trans 'Videos' %}</span>
        </div>
        <div class="actions-detail col-xs-12 text-right">
            <span>
            <a href="https://twitter.com/share" class="twitter-share-button" data-text="{{ playlist.title }}"
               data-hashtags="pythonizame">Tweet</a>
            </span>&nbsp&nbsp
            <span>
        <!-- Inserta esta etiqueta donde quieras que aparezca Botón Compartir. -->
        <div class="g-plus" data-action="share" data-annotation="bubble" data-href="{{ playlist.url }}"></div>
            </span>
            <span>{{ playlist.timestamp | date }}</span>&nbsp&nbsp
            <span class="post_like" data-id="{{ playlist.id }}"> <i
                    class="{% if i_like %} fa fa-heart postLike {% else %}fa fa-heart-o {% endif %}heart{{ playlist.id }}"></i> <small
                    class="num_likes{{ playlist.id }}">{{ playlist.num_likes }}</small></span>&nbsp&nbsp
            <span data-toggle="tooltip" data-placement="bottom" title="Quitar/Agregar de mis favoritos"
                  class="post_favorite" data-id="{{ playlist.id }}"> <i
                    class="{% if i_favorite %} fa fa-star postfavorite {% else %}fa fa-star {% endif %}favorite{{ playlist.id }}"></i></span>
        </div>
        <div class="hr col-xs-5" style="float: right"></div>

        <div class="post_content col-xs-12">
{#            <div class="banner_post_detailt" style="margin-bottom: 30px">#}
{#                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>#}
{#                <!-- post_detalle1 -->#}
{#                <ins class="adsbygoogle"#}
{#                     style="display:block"#}
{#                     data-ad-client="ca-pub-5267377707713164"#}
{#                     data-ad-slot="5925055247"#}
{#                     data-ad-format="auto"></ins>#}
{#                <script>#}
{#                    (adsbygoogle = window.adsbygoogle || []).push({});#}
{#                </script>#}
{#            </div>#}
            {{ playlist.description|safe }}
            <br/><br/>
            <div class="box-body table-responsive no-padding" style="height: 400px; overflow: paged-y">
              <table class="table table-striped">
              <thead>
              <tr>
                  <th width="10%"><h4>#</h4></th>
                  <th width="75%"><h4>Título</h4></th>
                  <th width="15%"> </th>
                </tr>
              </thead>
                <tbody>
                {% for video in playlist.video_set.all %}
                    <tr>
                        <td><h4>{{ video.order }}</h4></td>
                        <td>
                            <h4>{{ video.title }}</h4>
                            <p>{{ video.description|safe|truncatechars:150 }}</p>
                        </td>
                        <td><h4>
                            <a href="{% url 'videos:video-detail' video.id %}"> <i class="fa fa-play-circle text-danger"></i> {% trans 'Reproducir' %}
                            </a>
                        </h4>
                        </td>
                    </tr>
                {% endfor %}
              </tbody>
              </table>
            </div>
            <br><br>
            <blockquote>
                Pythonízame reconoce el gran esfuerzo de los autores de este contenido por
                compartir sus conocimientos a través de videos que ayudan a que más desarrolladores
                conozcan el gran potencial del lenguaje de programación Python.
            </blockquote>
            <div class="banner_post_detailt">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- Primera página - 3 (pythoniza.me) -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-5267377707713164"
                     data-ad-slot="9762554440"
                     data-ad-format="auto"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
            <div id="disqus_thread"></div>
        </div>

    </article>
{% endblock content %}
{% block aside_blog %}
    <div class="col-xs-12 no-padding">
        <div class="box box-primary">
            <div class="box-body box-profile">
                {% if playlist.author.userprofile.image %}
{#                    <a href="{% url 'account:profile' post.author.id %} ">#}
                        <img
                            src="{{ playlist.author.userprofile.avatar }}"
                            class="profile-user-img img-responsive img-circle"
                            alt=""
                            height="50px"/>
{#                    </a>#}
                {% else %}
{#                    <a href="{% url 'account:profile' post.author.id %} ">#}
                        <img src="{% static 'app/img/default.gif' %}"
                             class="profile-user-img img-responsive img-circle"
                             alt=""
                             height="50px"/>
{#                    </a>#}
                {% endif %}
                <h3 class="profile-username text-center">{{ playlist.author.first_name }} {{ playlist.author.last_name }}</h3>

                <p class="text-muted text-center">{{ playlist.author.userprofile.about_me }}</p>
            </div>
            <!-- /.box-body -->
        </div>
    </div>
{#    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding">#}
{#        <div class="box box-danger">#}
{#            <div class="box-header with-border">#}
{#                <h3 class="box-title">Etiquetas</h3>#}
{#            </div>#}
{#            <!-- /.box-header -->#}
{#            <div class="box-body">#}
{#                {% for my_tag in post.tags.all %}#}
{#                    <small class="fa fa-tag"><a href="{% url 'blog:by_tag' my_tag.slug %}"> {{ my_tag }}</a></small>#}
{#                {% endfor %}#}
{#                <!-- /.users-list -->#}
{#            </div>#}
{#            <!-- /.box-body -->#}
{#        </div>#}
{#    </div>#}
    <div class="col-lg-12 col-md-12 col-sm-6 col-xs-12 no-padding ">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Listas de reproducción similares</h3>

            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <ul class="products-list product-list-in-box">
                    {% for playlist_rel in related_playlist %}
                        <li class="item">
                            <div class="product-img">
                                <img src="{{ playlist_rel.cover|thumbnail_url:'pin_blog_image' }}"
                                     alt="{{ playlist_rel.title }}">
                            </div>
                            <div class="product-info">
                                <a href="{% url 'videos:playlist-detail' playlist_rel.slug %}"
                                   class="product-title">{{ playlist_rel.title }}
                                </a>
                                <span class="product-description">
                          Hace {{ playlist_rel.timestamp|timesince }}
                        </span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <!-- /.box-body -->
        </div>
    </div>
    <div class="col-xs-12 aside-item" style="padding:0;overflow-x:hidden ">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- index_blog -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:300px;height:250px"
             data-ad-client="ca-pub-5267377707713164"
             data-ad-slot="7659361247"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
{% endblock aside_blog %}
{% block scripts %}
    {% if config.enable_disqus %}
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES * * */
            var disqus_shortname = '{{ config.disqus_shortname }}';

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function () {
                var dsq = document.createElement('script');
                dsq.type = 'text/javascript';
                dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments
            powered by Disqus.</a></noscript>
    {% endif %}
{% endblock scripts %}

pythonizame/apps/videos/templates/video_detail.html
{% extends 'base_video.html' %}
{% load static thumbnail i18n %}
{% block title %} {{ video.title }}{% endblock title %}
{% block metas %}
    <meta name="description" content="{{ post.abstract }}">
    <meta name="keywords" itemprop="keywords" content="{% for my_tag in post.tags.all %}{{ my_tag }},{% endfor %}">
    <meta property="og:locale" content="es_MX"/>
    <meta property="og:type" content="article"/>
    <meta property="og:image" content="{{ video.playlist.cover|thumbnail_url:'main_blog_image' }}">
    <meta property="og:title" content="{{ video.title }}"/>
    <meta property="og:description" content="{{ video.abstract }}"/>
    <meta property="og:url" content="{{ video.url }}"/>
    <meta property="og:site_name" content="Pythonízame | {{ video.title }}"/>
{% endblock metas %}
{% block style %}
    <style>
    .videoWrapper {
	position: relative;
	padding-bottom: 56.25%; /* 16:9 */
	padding-top: 25px;
	height: 0;
}
.videoWrapper iframe {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
}

    </style>
{% endblock style %}
{% block content %}
    <article class="col-xs-12" id="detail_article">
        <div class="actions-detail col-xs-12 text-right">
            <div class="hr col-xs-5" style="float: right"></div>
            <div class="post_content col-xs-12">
                <div class="videoWrapper text-center" style="margin-top: 10px">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
{#                    <iframe width="100%" height="400"#}
{#                            src="{{ video.url }}"#}
{#                            src="https://youtu.be/WW1wonc_zIs"#}
{#                            frameborder="0"></iframe>#}
{#                    <iframe width="100%" height="400"#}
{#                            src="http://www.youtube.com/embed/M7lc1UVf-VE?autoplay=1&origin=http://example.com"#}
{#                            frameborder="0"#}
{#                            allow="autoplay; encrypted-media" allowfullscreen></iframe>#}
                </div>
                <div class="video-description text-left" style="font-size: 15px; margin-top: 20px">
                    {{ video.description|safe }}
                </div>
                <div class="banner_post_detailt">
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Primera página - 3 (pythoniza.me) -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-5267377707713164"
                         data-ad-slot="9762554440"
                         data-ad-format="auto"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
                <div id="disqus_thread"></div>
            </div>
    </article>
{% endblock content %}
{% block aside_blog %}
    <div class="col-xs-12 no-padding">
        <div class="box box-danger">
            <div class="box-body box-profile">
                {% if video.playlist.cover %}
                    <a href="{% url 'videos:playlist-detail' video.playlist.slug %}"><img
                            src="{{ video.playlist.cover|thumbnail_url:"main_blog_image" }}"
                            class="img-responsive"
                            alt=""
                            height="50px"/>
                    </a>
                    {#                    </a>#}
                {% else %}
                    {#                    <a href="{% url 'account:profile' post.author.id %} ">#}
                    <img src="{% static 'app/img/default.gif' %}"
                         class="profile-user-img img-responsive img-circle"
                         alt=""
                         height="50px"/>
                    {#                    </a>#}
                {% endif %}
                <h3 class="profile-username text-center">{{ video.author.first_name }} {{ video.author.last_name }}</h3>

                <p class="text-muted text-center">{{ video.author.userprofile.about_me }}</p>
            </div>
            <!-- /.box-body -->
        </div>
    </div>
    {#    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding">#}
    {#        <div class="box box-danger">#}
    {#            <div class="box-header with-border">#}
    {#                <h3 class="box-title">Etiquetas</h3>#}
    {#            </div>#}
    {#            <!-- /.box-header -->#}
    {#            <div class="box-body">#}
    {#                {% for my_tag in post.tags.all %}#}
    {#                    <small class="fa fa-tag"><a href="{% url 'blog:by_tag' my_tag.slug %}"> {{ my_tag }}</a></small>#}
    {#                {% endfor %}#}
    {#                <!-- /.users-list -->#}
    {#            </div>#}
    {#            <!-- /.box-body -->#}
    {#        </div>#}
    {#    </div>#}
    <div class="col-lg-12 col-md-12 col-sm-6 col-xs-12 no-padding ">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">Listas de reproducción</h3>
                <div class="box-body table-responsive no-padding" style="height: 400px; overflow: paged-y">
                    <table class="table table-hover">
                        <tbody>
                        <tr>
                            <th>#</th>
                            <th>{% trans 'Título' %}</th>
                        </tr>
                        {% for video_play in video.playlist.video_set.all %}
                            <tr>
                            <td>{{ video_play.order }}</td>
                                <td>
                                    <small>
                                        <a href="{% url 'videos:video-detail' video_play.id %}">{{ video_play.title }}</a>
                                        <span style="font-size: 8px" class="text-danger">
                                            {% if video_play.id == video.id %}
                                                / {% trans 'Reproduciendo' %}
                                            {% endif %}
                                        </span>
                                    </small>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <ul class="products-list product-list-in-box">
                    {% for video_rel in related_video %}
                        <li class="item">
                            <div class="product-img">
                                <img src="{{ video_rel.cover|thumbnail_url:'pin_blog_image' }}"
                                     alt="{{ video_rel.title }}">
                            </div>
                            <div class="product-info">
                                <a href="{% url 'blog:post_detail' video_rel.slug %}"
                                   class="product-title">{{ video_rel.title }}
                                </a>
                                <span class="product-description">
                          Hace {{ video_rel.timestamp|timesince }}
                        </span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <!-- /.box-body -->
        </div>
    </div>
    <div class="col-xs-12 aside-item" style="padding:0;overflow-x:hidden ">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- index_blog -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:300px;height:250px"
             data-ad-client="ca-pub-5267377707713164"
             data-ad-slot="7659361247"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
{% endblock aside_blog %}
{% block scripts %}
    {% if config.enable_disqus %}
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES * * */
            var disqus_shortname = '{{ config.disqus_shortname }}';

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function () {
                var dsq = document.createElement('script');
                dsq.type = 'text/javascript';
                dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments
            powered by Disqus.</a></noscript>
    {% endif %}
{% endblock scripts %}